### ISSUE TITLE
Pip2 Error

### ISSUE THREAD

**Issue by SamuelGabriel** [f-dangel/backpack#81]
If I try to install with pip2 I get the following error:

 ```
pip install backpack-for-pytorch
Collecting backpack-for-pytorch
  Using cached https://files.pythonhosted.org/packages/33/1e/c54c4e36aa5ae67117f03410d60c363779620b7aa78b0c67245af23f45c7/backpack-for-pytorch-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gl/53ck005n3cj8_08d_zzt4jcc0000gn/T/pip-install-T8akay/backpack-for-pytorch/setup.py", line 23, in <module>
        with open(REQUIREMENTS_FILE) as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gl/53ck005n3cj8_08d_zzt4jcc0000gn/T/pip-install-T8akay/backpack-for-pytorch/
```

**Comment by fKunstner** [comment]
Hi Samuel, thanks for the report. 

By `pip2` I assume it's a version of pip for python `2.X`? The error message is criptic, but likely because Python 2 is not supported. 
You'll need Python 3.5+ (Backpack uses Python 3 syntax and PyTorch dropped Python 2 support as well this year)
